openapi: 3.0.0
servers:
  - description: STAGING (MOCK)
    url: http://localhost:8080
  - description: STAGING
    url: http://localhost:8080
  - description: PROD
    url: http://localhost:8080
info:
  description: Auth API
  version: 2.0.0
  title: Auth API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: auth
    description: Auth operations
paths:
  /auth/login/v1:
    post:
      tags:
        - auth
      summary: login
      operationId: authLoginV1
      description: login and return token
      responses:
        '200':
          $ref: '#/components/schemas/AuthV1Response'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthV1Request'
components:
  schemas:
    AuthV1Request:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: hronom
        password:
          type: string
          example: hronom
    AuthV1Response:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          example: 111
