openapi: 3.0.0
servers:
  - description: Swagger Proxy URL
    url: http://localhost:8080
info:
  description: User Search V2 API
  version: 2.0.0
  title: User Search V2 API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admin
    description: Admin operations
  - name: search
    description: Search operations
paths:
  /admin/ping/v1:
    get:
      tags:
        - admin
      summary: ping
      operationId: adminPingV1
      description: ping
      responses:
        '200':
          description: pong
  /search/common/v1:
    post:
      tags:
        - search
      summary: search
      operationId: searchCommonV1
      description: search items in system
      responses:
        '200':
          $ref: '#/components/schemas/CommonV1Response'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommonV1Request'
        description: Common Search Request V1
  /search/common/v2:
    post:
      tags:
        - search
      summary: search
      operationId: searchCommonV2
      description: search items in system
      responses:
        '200':
          $ref: '#/components/schemas/CommonV2Response'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommonV2Request'
        description: Common Search Request V2
components:
  schemas:
    CommonV1Request:
      type: object
      required:
        - userQuery
      properties:
        userQuery:
          type: string
          example: what is OpenAPI?
    CommonV1Response:
      type: array
      items:
        $ref: '#/components/schemas/ItemV1'
    ItemV1:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          example: 111
        name:
          type: string
          example: ACME Corporation
    CommonV2Request:
      type: object
      required:
        - userQuery
        - filter
      properties:
        userQuery:
          type: string
          example: what is OpenAPI?
        filter:
          type: boolean
          example: true
    CommonV2Response:
      type: array
      items:
        $ref: '#/components/schemas/ItemV2'
    ItemV2:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          example: 111
        name:
          type: string
          example: ACME Corporation
